# Generated by Django 4.2.2 on 2023-07-21 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='nimi', max_length=100)),
                ('category', models.CharField(default='All', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('price1', models.IntegerField(blank=True, null=True)),
                ('source1', models.CharField(blank=True, max_length=100, null=True)),
                ('price2', models.IntegerField(blank=True, null=True)),
                ('source2', models.CharField(blank=True, max_length=100, null=True)),
                ('price3', models.IntegerField(blank=True, null=True)),
                ('source3', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('email', models.CharField(default='beintouch01@gmail.com', max_length=100)),
                ('password', models.CharField(default='123456', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('invoice_number', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='EUR', max_length=100)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('cardholder_name', models.CharField(default='John Doe', max_length=100)),
                ('card_number', models.CharField(default='0000 0000 0000 0000', max_length=100)),
                ('expiration_date', models.CharField(default='01/01', max_length=5)),
                ('cvv', models.CharField(default='000', max_length=3)),
                ('billing_address', models.CharField(default='Street 1, City, Country', max_length=100)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='halpaa_hinta.users')),
            ],
            options={
                'ordering': ['invoice_number', 'user', 'payment_status', 'amount', 'currency', 'transaction_date', 'cardholder_name', 'card_number', 'expiration_date', 'cvv', 'billing_address', 'shipping_address', 'description', 'last_updated'],
            },
        ),
    ]
