# Generated by Django 4.2.2 on 2023-07-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halpaa_hinta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['user']},
        ),
    ]
