# Generated by Django 4.2.2 on 2023-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halpaa_hinta', '0002_alter_payments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
