# Generated by Django 4.2.2 on 2023-07-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halpaa_hinta', '0002_remove_products_image_payments_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image1',
            new_name='image',
        ),
    ]
