# Generated by Django 4.2.2 on 2023-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halpaa_hinta', '0003_alter_payments_options_rename_image_products_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(default='credit card', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='source1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='source2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='source3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
