# Generated by Django 4.2.2 on 2023-07-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halpaa_hinta', '0004_payments_payment_type_alter_products_source1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
